name: margueritesheehan@mac.com
favicon: null
layout_spectrum: 0.9519680116791278
typography_spectrum: 0.06375695485621691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#aebab6'
    - '#3f3f3f'
    - '#7a8273'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
